### ISSUE TITLE
long sequences of _ do not encrypt well

### ISSUE THREAD

**Issue by lyosha** [exaexa/ls47#1]

**Comment by exaexa** [comment]
I guess you're referring to this problem:
```
>>> ls47.encrypt(k,'b______________________________________________________')
'r?326jp?azib___________________________________________'
```
(also present in original ls4)

We kindof assume that humans won't really want to encode long sequences of perfectly same characters, especially spaces. Padding this out is easily possible, but not included since it's boring. ( :] )

Note that a similar thing (finding cycles) is possible also with other characters and character sequences, but with _much_ lower probability (also with much lower probability than in ls4, since the size of array is prime).

Best chance for a fix would probably be something that avoids the fixpoint from occurring -- like, in rc4, having a counter and updating the state based on the counter. Maybe just adding one-move rotations would be sufficient.

Would you propose your favorite solution, if you have one?

**Comment by lyosha** [comment]
I don't have anything to propose, unfortunately. In the original paper I saw LS4 being compared to RC4, so I assumed it would work reasonably well on any kind of data.

I imagine if you apply run-length encoding to your input, that would solve this particular problem. Though it seems like a workaround, rather than a proper solution.

**Comment by exaexa** [comment]
Turns out that _carrying the marker_ with the rotations while doing encryption is to blame -- it creates a really simple possibility for getting the encryption to a fixpoint.

Btw. ElsieFour paper says: If the marker’s tile moves, the marker stays on that tile.

Guess we should change that.
